### ISSUE TITLE
حالت sandbox

### ISSUE THREAD

**Issue by mamadjavadrasty** [omalizadeh/laravel-multi-payment#13]
سلام خسته نباشی
درکل پکیج خوبیه فقط حالت sandbox برای زرین پال کار نمیکنه ولی مثل اینکه میشه این مشکل رو برطرف کرد . اگه فرصت کردید این مشکل رو برطرف کنید خیلی خوب میشه

**Comment by omalizadeh** [comment]
<div dir="rtl">
سلام. آخرین بار که استفاده کردم، مشکل از سمت زرین‌پال بود. از اونجایی که دوستان اونجا خیلی خوب کار می‌کنن (!) مطمئن نیستم مشکل حل شده باشه، اما اگه شما بررسی کردید و دیدید قابل برطرف شدنه و مشکل از سمت پکیجه، خوشحال میشم پول رکوئست بزنید. مرسی.

@mamadjavadrasty 
</div>
