### ISSUE TITLE
Bug Report - Incorrect 'pin' Key in 'gateway_parsian.php'

### ISSUE THREAD

**Issue by majidfeiz** [omalizadeh/laravel-multi-payment#15]
I recently installed omalizadeh/laravel-multi-payment version ^2.6 and encountered an issue where the application was throwing a "pin not found" error. After investigating the problem, I found that the issue lies in the configuration file gateway_parsian.php. The key pin should be replaced with pin_code for proper functionality.

## Steps to Reproduce:

    Install the omalizadeh/laravel-multi-payment package version ^2.6.
    Attempt to use the Parsian gateway within the package.

## Expected Behavior:

The package should work correctly without any errors related to the 'pin' key.

 ## Actual Behavior:

The package throws an error mentioning that the 'pin' key is not found.

## Additional Information:

The issue can be resolved by changing the 'pin' key to 'pin_code' in the gateway_parsian.php configuration file.

Thank you for your attention to this matter. If you need further information or assistance, please let me know.

Sincerely,

Majid Feiz

**Comment by omalizadeh** [comment]
hi.
i couldn't seen any 'pin' key in v2.x branch, it's all `pin_code` like the driver itself. maybe you upgraded from 2.6 to 3.0 and didn't update any config file in your project? i changed pin_code to pin according to parsian documentation in new major version.
@majidfeiz
