### ISSUE TITLE
خطا

### ISSUE THREAD

**Issue by aliinjectorr** [omalizadeh/laravel-multi-payment#16]
سلام وقت بخیر
من دقیقا براساس کد های داکیومنت پیش رفتم اما موقعی که میخواد ریدایرکت بشه به درگاه این خطا رو میده:
پارامترهای ارسال شده نامعتبر است.; مبلغ تراکنش کمتر از 1,000 ریال قابل قبول نیست

**Comment by omalizadeh** [comment]
سلام
خطا واضحه متنش، مبلغی که سمت درگاه فرستادید کمه و درگاه قبول نمیکنه. از حداقل 1000 تومان برای درگاه استفاده کنید. بهتره اگه از کد تخفیف توی سیستم استفاده می‌کنید قبل از ارجاع به درگاه، چک کنید از 1000 تومان کمتر نباشه.
@aliinjectorr
