### ISSUE TITLE
خطای 419 هنگام بازگشت از درگاه

### ISSUE THREAD

**Issue by ferasat** [omalizadeh/laravel-multi-payment#21]
سلام
من طبق مستندات پیش رفتم ولی وقتی از درگاه بر می گردد صفحه :
419
PAGE EXPIRED
میاد بالا .
لوکال دارم تست می کنم .

**Comment by omalizadeh** [comment]
سلام
فکر نمی‌کنم مرتبط با کدهای خود پکیج باشه
متد رکوئست بازگشت از درگاه، کدهای ویویی که می‌خواید نمایش بدید و مسئله CSRF توکن رو بررسی کنید، احتمالا مرتبط با ایناست.
@ferasat

**Comment by ferasat** [comment]
من طبق راهنما پیش رفته ام و  بازگشت را در فایل مثلا gateway_idpay  به :
`'callback_url' => 'http://127.0.0.1:8080/in_pay/result',`
ست کردم .
و در این روت در کنترلر یک dd گذاشتم ببینم چی  بر میگردونه ولی کلا ارور 419 میده

**Comment by omalizadeh** [comment]
گفته بودم توکن CSRF رو بررسی کنید
روت بازگشت توی وب تعریف کردید؟ متدش پسته؟
اگه اینطوریه باید توی میدل ور VerifyCsrfToken این روت رو استثنا کنید
این مورد مرتبط با خود لاراوله
@ferasat

**Comment by ferasat** [comment]
بله حرف شما درست بود .
باید در فایل 
app\Http\Middleware\VerifyCsrfToken.php
اون مسیر را استثنا می کردم .
من با روش های دیگر سعی کردم مسیر را مستثنا کنم که نشد و اعمال نمی کرد.

ممنون از شما مشکل من حل شد .
@omalizadeh
