### ISSUE TITLE
MultiPayment\Exceptions\HttpRequestFailedException

### ISSUE THREAD

**Issue by mamadjavadrasti** [omalizadeh/laravel-multi-payment#9]
سلام خسته نباشید
من با این ارور مواجه شدم و روی لوکال دارم تست میکنم
مربوط به ssl هست؟
اگه مربوط به ssl  میشه بفرمایید روی لاراول چجوری ssl رو فعال کنم 
ممنون

**Comment by omalizadeh** [comment]
سلام
شما فقط نوع اکسپشن رو فرستادید، متن پیامش رو هم میفرستادید.
اگه خطای ssl بوده، باید توی php.ini تنظیمات انجام بدید.
این لینک فکر کنم کمک کننده باشه.
https://stackoverflow.com/questions/42094842/curl-error-60-ssl-certificate-in-laravel-5-4
